### ISSUE TITLE
Harcoded Upvote in Feedback Dialog

### ISSUE THREAD

**Issue by alexigityan** [rasjonell/course_review#6]
We have this bit of code in `<FeedbackDialog />` :
 const handleSubmit = e => {
    ...
      **upvote: { [user.uid]: true },
      downvote: {},**
    ...
  };

So whenever user leaves feedback via this dialog, the course gets an upvote.
During first sign-in the user needs to select two courses - best and worst - and leave a feedback to proceed. As a result, the worst course actually gets an upvote from the user.

![Screenshot](https://user-images.githubusercontent.com/40140063/60279244-be6fc300-9911-11e9-8e1e-fb8300fe4cb7.png)

**Comment by rasjonell-gruv** [comment]
Sorry for the late response, I'm currently working on a separate side project that can more efficiently solve the main problem of Course Reviews.

Regarding your concern, this was done intentionally, since you don't rate courses you rate the feedback, so similar to Reddit all your posts get automatically upvoted by yourself.

**Comment by alexigityan** [comment]
Okay, i misinterpreted it as an upvote to the course itself, not the feedback. Closing the issue then
